version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ;2=BRhi*LoRI
      MYSQL_DATABASE: miodb
    ports:
      - "3307:3306"
